### ISSUE TITLE
cannt work

### ISSUE THREAD

**Issue by 2797635026** [webpilot-ai/Webpilot#88]
The console is reporting an error. The extension can be installed but cannot run. I am using the ChatGPT API key and I don’t know where the error occurred. 
![Uploading Snipaste_2023-11-04_19-38-53.png…]
![Snipaste_2023-11-04_19-42-54](https://github.com/webpilot-ai/Webpilot/assets/77963683/eac953f5-f5cc-45df-b705-a826dbd27ff1)

![Snipaste_2023-11-04_19-41-52](https://github.com/webpilot-ai/Webpilot/assets/77963683/cce995d6-5d58-44ba-81e1-018490975cbc)
()

**Comment by 2797635026** [comment]
mail     wangyangbing66c@gmail.com

**Comment by CocoSgt** [comment]
Can I see the video demonstration and the detailed content in the network(in F12)?

**Comment by 2797635026** [comment]
> Can I see the video demonstration and the detailed content in the network(in F12)?

![IMG_20231104_234402.jpg](https://github.com/webpilot-ai/Webpilot/assets/77963683/852dffca-0634-4471-8fc4-de66da0ba0bf)

AST library loaded: 0.58.0
api.msn.com/segments/recoitems/LiveRampObjectStoreCaller?apikey=0QfOX3Vn51YCzitbLaRkTTBadtWpgTN8NZLW0C1SEM&activityId=778780D0-AD4F-4C28-AD65-9BC792656251&ocid=peregrine&cm=zh-cn&it=edgeid&user=m-3FA902784EA860D4043D10BC4F7A61D1&traceparent=00-13b4c210594f423fbc43f650f1a3cd03-e64721e19fdc45d4-00:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
15Failed to decode downloaded font: <URL>
15OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
assets.msn.cn/service/msn/user?apikey=0QfOX3Vn51YCzitbLaRkTTBadtWpgTN8NZLW0C1SEM&activityId=778780D0-AD4F-4C28-AD65-9BC792656251&ocid=pdp-peregrine&cm=zh-cn&it=edgeid&user=m-3FA902784EA860D4043D10BC4F7A61D1&traceparent=00-6c94e62859984c5494163a77b8ebfdba-f5ae2dde225848f0-00:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
common.6471937ed2a0284d98bc.js:7  Sat Nov 04 2023 23:33:31 GMT+0800 (中国标准时间): 1699112011795 {"id":20153,"severity":0,"pb":{"build":"20231102.271","appType":"views","pcsVersion":"20231102.5_master","pcsEnv":"prod","buildAlias":"latest","shouldDelayUntilLoadTime":false,"shouldSupressWarnings":false,"customMessage":"Status: 204, StatusText: ","w":1},"message":"No content received from SAMRTB Ajax"}
(anonymous) @ common.6471937ed2a0284d98bc.js:7
common.6471937ed2a0284d98bc.js:7  Sat Nov 04 2023 23:33:31 GMT+0800 (中国标准时间): 1699112011855 {"id":20153,"severity":0,"pb":{"build":"20231102.271","appType":"views","pcsVersion":"20231102.5_master","pcsEnv":"prod","buildAlias":"latest","shouldDelayUntilLoadTime":false,"shouldSupressWarnings":false,"customMessage":"Status: 204, StatusText: ","w":1},"message":"No content received from SAMRTB Ajax"}
(anonymous) @ common.6471937ed2a0284d98bc.js:7
common.6471937ed2a0284d98bc.js:7  Sat Nov 04 2023 23:33:31 GMT+0800 (中国标准时间): 1699112011926 {"id":20153,"severity":0,"pb":{"build":"20231102.271","appType":"views","pcsVersion":"20231102.5_master","pcsEnv":"prod","buildAlias":"latest","shouldDelayUntilLoad

**Comment by CocoSgt** [comment]
I checked the website msn.cn and found many errors, which seem to be caused by the website itself. I also tried using WebPilot on this website, and it worked fine.

Just a guess, is there a problem with your API proxy? Maybe it should be api.chatnio.net/something instead of  api.chatnio.net.

Can you try connecting directly to OpenAI's API first? Or maybe the WebPilot API? Just to see if they can be used properly?

One more question, after clicking the prompt, is there no response, no result, or an error?

**Comment by 2797635026** [comment]
email you video

**Comment by CocoSgt** [comment]
I checked your email and understand why:

You have used this as a key relay proxy:
https://docs.chatnio.net/developer-resources/api-reference/key-relay
It is required to change the request URL for OpenAI from api.openai.com to api.chatnio.net, rather than using api.openai.net directly.

The request URL for OpenAI comes with a suffix, it seems to be https:api.openai.com/v1 , or possibly others
